chore: adding Nebula as GH owners
snyk/vscode-extension pull request #367
Opened 2023-07-10 07:01 UTC by metju90

Adding team Nebula as code owners for files that could break local-engine

2023-07-10 07:02 UTC, metju90 commented on .github/CODEOWNERS
> +src/test/unit/snykCode/codeSettings.test.ts @snyk/nebula
`@snyk/owl` does not seem to exist anymore

2023-07-10 10:47 UTC, bastiandoetsch requested changes
Hi @metju90 , I'll discuss with the team, if we want code-ownership of the codeSettings in VSCode with Nebula.

2023-07-10 11:43 UTC, metju90 commented
> Hi @metju90 , I'll discuss with the team, if we want code-ownership of the codeSettings in VSCode with Nebula.

@bastiandoetsch shared ownership will be best. We want to be notified of potentially breaking changes for local-engine.

2023-07-12 07:56 UTC, metju90 commented
@bastiandoetsch Code files are now co-owned between hammerhead, zenith and nebula

2023-07-12 08:24 UTC, bastiandoetsch approved these changes

2023-07-12 08:24 UTC, merged