feat: display branch selection in the tree node [IDE-446]
snyk/vscode-extension pull request #489
Opened 2024-07-12 14:13 UTC by acke

### Description

This pr covers the UI parts of selecting a base branch for delta findings. No actually calls to language server for available local branches, or to set the choose branch is a part of this pr.

This PR handles tree view for Security Code and Code Quality depending on the Delta Findings feature flag. When enabled, the title for the tree node shows

- Code Security - New Issues
- Code Quality - New Issues

### Checklist

- [ ] Tests added and all succeed
- [ ] Linted
- [ ] CHANGELOG.md updated
- [ ] README.md updated, if user-facing

### Screenshots / GIFs

https://github.com/user-attachments/assets/9fe4ede8-c2bf-481d-8698-46decb49c096

2024-07-16 06:11 UTC, bastiandoetsch commented on src/snyk/common/commands/commandController.ts
> +  }
this will probably not stay like this, but use a setting

2024-07-16 06:19 UTC, bastiandoetsch requested changes
I think this needs to wait until the LS side is implemented for correct integration. Correct me, if there's another story that handles the LS integration.

2024-07-16 17:13 UTC, cat2608 commented on src/snyk/common/views/issueTreeProvider.ts
> +    return `Snyk found ${nIssues} issue${nIssues === 1 ? '' : 's'}`;
Small refactor for consistency. Agreed with Arvrid and Neil 🙌 

|Before|After|
|-|-|
|<img width="550" alt="before" src="https://github.com/user-attachments/assets/49b9f1fc-ea99-4f48-989e-a3ea800e6d3f">|<img width="541" alt="after" src="https://github.com/user-attachments/assets/56f29de3-4562-442e-a50f-b07b369b8075">|

2024-07-16 17:17 UTC, cat2608 commented on package.json
> +          "when": "view == 'snyk.views.analysis.code.security' || view == 'snyk.views.analysis.code.security.delta' || view == 'snyk.views.analysis.code.quality' || view == 'snyk.views.analysis.code.
This adds the gear ⚙️ and play ▶️ buttons on the right of the title

2024-07-17 05:52 UTC, bastiandoetsch commented on src/snyk/snykCode/views/securityIssueTreeProvider.ts
>          text = `${nIssues} vulnerability found by Snyk`;
Shouldn't this be issues, too?

2024-07-17 05:52 UTC, bastiandoetsch commented on src/snyk/snykCode/views/securityIssueTreeProvider.ts
>          text = `✋ ${nIssues} vulnerabilities found by Snyk`;
```suggestion
        text = `✋ ${nIssues} issues found by Snyk`;
```

2024-07-17 05:55 UTC, bastiandoetsch commented on src/snyk/common/views/issueTreeProvider.ts
> +    //TODO: get the actual base branch from Snyk Language Server
This should just ask a config setting, what's the base branch for the folder. LS sends a folderConfig notification for all known workspace folders when they are registered at LS.

2024-07-17 06:07 UTC, bastiandoetsch approved these changes

2024-07-17 11:11 UTC, ShawkyZ approved these changes

2024-07-17 12:46 UTC, merged